version: 2.1

orbs:
  maven: circleci/maven@1.0.0

jobs:
  generate_javadoc:
    working_directory: ~/ing-sw-2020-Riva-Sanvito-Truong

    docker:
      - image: circleci/openjdk:13-jdk-buster

    steps:
      - checkout
      - run:
          name: Configure git user
          command: |
            git config user.email "ci-build@arcloud.it"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "85:53:74:17:3d:df:9e:92:91:97:95:3e:96:09:c5:ec"
      - run:
          name: Generate javadoc
          command: |
            javadoc \
              -sourcepath src/main/java \
              -d docs/javadoc \
              -private \
              -subpackages \
              it.polimi.ingsw
      - store_artifacts:
          path: docs/javadoc
      - run:
          name: Commit new artifacts path
          command: |
            cat \<<EOF > docs/javadoc/README.md
            # javadocs

            Head to the latest [CircleCI build artifacts](https://${CIRCLE_BUILD_NUM}-244441529-gh.circle-artifacts.com/0/docs/javadoc/index.html) to access the javadoc for the project.

            N.B.: you need to be [authenticated to CircleCI](https://circleci.com/vcs-authorize/) in order to access the build artifacts.
            EOF

            git add docs/javadoc/*
            git commit -m "docs(javadoc): update javadoc [skip ci]"
            git push --set-upstream origin ${CIRCLE_BRANCH}

workflows:
  master_push:
    jobs:
      - generate_javadoc
#      - maven/test:
#          command: '-X verify'
