version: 2.1

orbs:
  maven: circleci/maven@1.0.0

jobs:
  generate_javadoc:
    working_directory: ~/ing-sw-2020-Riva-Sanvito-Truong

    docker:
      - image: circleci/openjdk:13-jdk-buster

    steps:
      - checkout
      - run:
          name: Generate javadoc
          command: |
            javadoc \
              -sourcepath src\main\java \
              -d javadoc \
              -private \
              -subpackages \
              it.polimi.ingsw
      - store_artifacts:
          path: javadoc

workflows:
  master_push:
    jobs:
      - generate_javadoc
#      - maven/test:
#          command: '-X verify'
